crud/urls.py
from django.contrib import admin
from django.urls import path
import blog.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog.views.home, name='home'),  # 인덱스 페이지 _ Read
    path('blog/newblog/', blog.views.blogform, name='newblog'),  # create
    path('blog/<int:pk>/edit/', blog.views.edit, name='edit'),  # edit
    path('blog/<int:pk>/remove/', blog.views.remove, name='remove'),  # delete
    # path('blog/lay', blog.views.MainpageView.as_view(), name='mainpage')
    path('blog/<int:blog_id>/comment/', blog.views.detail, name='comment'),
    path('blog/<int:blog_id>/comment_edit/<int:pk>/', blog.views.comment_edit, name='comment_edit'),
    path('blog/<int:blog_id>/comment_remove/<int:pk>/', blog.views.comment_remove, name='comment_remove'),
    path('blog/hashtag/', blog.views.hashtagform, name='hashtag'),
    path('blog/<int:hashtag_id>/search/', blog.views.search, name='search'),
]

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)            # 타이틀
    pub_date = models.DateTimeField('date published')   # 날짜
    body = models.TextField()                           # 내용  
    hashtags = models.ManyToManyField('Hashtag', blank=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="comments")
    comment_text = models.CharField(max_length=50)

    def __str__(self):
        return self.comment_text

class Hashtag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Blog, Comment, Hashtag

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title','body','hashtags']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["comment_text"]

class HashtagForm(forms.ModelForm):
    class Meta:
        model = Hashtag
        fields = ['name']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .forms import BlogForm, CommentForm, HashtagForm
from .models import Blog, Comment, Hashtag
# Create your views here.

# Read
def home(request):
    blogs = Blog.objects
    hashtags = Hashtag.objects
    return render(request, 'blog/home.html', {'blogs': blogs, 'hashtags': hashtags})

# Create
def blogform(request, blog=None):       
    if request.method == 'POST':
        form = BlogForm(request.POST, instance=blog)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.pub_date = timezone.now()
            blog.save()
            form.save_m2m()
            return redirect('home')
    else:
        form = BlogForm(instance=blog)
        return render(request, 'blog/new.html', {'form': form})

# Edit
def edit(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    return blogform(request, blog)

# Delete
def remove(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    blog.delete()
    return redirect('home')

#댓글생성
def detail(request, blog_id, comment=None):
        blog = get_object_or_404(Blog, id = blog_id)
        if request.method == "POST":
                form = CommentForm(request.POST, instance=comment)
                if form.is_valid():
                        comment = form.save(commit=False)
                        comment.blog = blog
                        comment.comment_text = form.cleaned_data["comment_text"]
                        comment.save()
                        return redirect("home")

        else:
                form = CommentForm(instance=comment)
                return render(request, "blog/detail.html", {"blog":blog, "form":form})

def comment_edit(request, blog_id, pk):
        comment = get_object_or_404(Comment, pk=pk)
        return detail(request, blog_id, comment)

def comment_remove(request, blog_id, pk):
        comment = get_object_or_404(Comment, pk=pk)
        comment.delete()
        return redirect('home')

def hashtagform(request, hashtag=None):
        if request.method == 'POST':
                form = HashtagForm(request.POST, instance=hashtag)
                if form.is_valid():
                        hashtag = form.save(commit=False)
                        if Hashtag.objects.filter(name=form.cleaned_data['name']):
                                form = HashtagForm()
                                error_message = "♨이미 존재하는 해시태그입니당♨"
                                return render(request, 'blog/hashtag.html', {'form':form, "error_message":error_message})
                        else:
                                hashtag.name = form.cleaned_data['name']
                                hashtag.save()
                                return redirect('home')
        else:
                form = HashtagForm(instance=hashtag)
                return render(request, 'blog/hashtag.html', {'form':form})

def search(request, hashtag_id):
        hashtag = get_object_or_404(Hashtag, pk=hashtag_id)
        return render(request, 'blog/search.html', {'hashtag': hashtag})

blog/templates/blog/detail.html
{% extends 'index.html' %}
{% load staticfiles%}

{% block content %}
<h2 class="text-center text-uppercase text-secondary mb-0">댓글을 써주세용( ღ'ᴗ'ღ )</h2><br>
<form method="post">
    {% csrf_token %}
   <center> &nbsp;  {{form}} &nbsp; 
    <input class = "btn btn-primary" type="submit" value="댓글생성"></center>
</form>

{% endblock %}

blog/templates/blog/edit.html
{% extends 'index.html' %}
{% load staticfiles%}
     <h2 class="text-center text-uppercase text-secondary mb-0">글을 수정해주세용( ღ'ᴗ'ღ )</h2><br>
{% block content %}

  {% for blog in blogs.all %}
    <div class="card">
      <h5 class="card-header">{{ blog.title }}</h5>
 
      <div class="card-body">
  

        <form method="POST">
         {% csrf_token %}
            {{form.as_table}}
        <button type = "submit" class="btn btn-primary">저어장</button>
        </form>
      </div>
    </div>
  {% endfor %}

{% endblock %}

blog/templates/blog/hashtag.html
{% extends 'index.html' %}
{% load staticfiles%}

{% block content %}
<h2 class="text-center text-uppercase text-secondary mb-0">해시태그를 추가해주세요( ღ'ᴗ'ღ )</h2><br>
    <div class="card">
        <h5 class="card-header">{{ blog.title }}</h5>
        <div class="card-body">
        
       <center><font color="red"> {{ error_message }}</font> </center>
            <form method = 'POST'>
            {% csrf_token %}
            <center><table>
                {{form.as_table}}
            </table>    
            <input class="btn btn-primary" type="submit" value="태그생성"><center>
            </form>
        </div>
    </div>
{% endblock %}

blog/templates/blog/home.html
{% extends 'index.html' %}
{% load staticfiles%}

{% block content %}
<h2 class="text-center text-uppercase text-secondary mb-0">list( ღ'ᴗ'ღ )</h2><br>
 <!-- 해시태그 목록찾기 -->
 <div class="dropdown">
  <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Hashtag 검색
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    {% for hashtag in hashtags.all %}
    <a class="dropdown-item" href="{% url 'search' hashtag.id %}">{{ hashtag.name }}</a>
    {% endfor %}
  
  </div>
</div>
 
  {% for blog in blogs.all %}
    <div class="card">
      <h5 class="card-header">{{ blog.title }}</h5>
      <div class="card-body">
        <h5 class="card-title">{{ blog.body }}</h5>
        <p class="card-text">{{ blog.pub_date }}</p>
        
        <!-- 해시태그 목록 보이는 곳 -->
        {% for hashtag in blog.hashtags.all %}
          <span>{{ hashtag.name }}</span>
        {% endfor %}
        <br>
        <a href="{% url 'edit' pk=blog.pk %}" class="btn btn-primary">수정</a>
        <a href="{% url 'remove' pk=blog.pk %}" class="btn btn-primary">삭제</a>
        <a role="button" class="btn btn-primary" href="{% url 'comment' blog.id %}">댓글</a>

        <hr>
        <div>
          {% for comment in blog.comments.all %}
        <p> {{ comment }} </p>
          <div class = "button">
            <a role="button" class="btn-outline-secondary" href="{% url 'comment_edit' blog.id comment.id %}">댓글수정</a>
            <a role="button" class="btn-outline-danger" href="{% url 'comment_remove' blog.id comment.id %}">댓글삭제</a>
         
          </div>
        {% endfor %}
      </div>
    </div>
    <br>
  {% endfor %}

{% endblock %}

blog/templates/blog/new.html
{% extends 'index.html' %}
{% load staticfiles%}

{% block content %}

    <div class="card">
        <h5 class="card-header">{{ blog.title }}</h5>
        <div class="card-body">
            <form method = 'POST'>
            {% csrf_token %}
            <center><table>
                {{form.as_table}}
            </table>    
            <input class="btn btn-dark" type="submit" value="제출하기"><center>
            </form>
        </div>
    </div>
{% endblock %}

blog/templates/blog/search.html
{% extends 'index.html' %}
{% load staticfiles%}

{% block content %}
<h2 class="text-center text-uppercase text-secondary mb-0">해시태그 검색결과 페이지( ღ'ᴗ'ღ )</h2><br>
<h3> ' {{ hashtag }} ' 태그가 있는 게시글 목록 </h3>

    {% for blog in hashtag.blog_set.all %}
        <div class="card">
            <h5 class="card-header">{{ blog.title }}</h5>
        <div class="card-body">
            <h5 class="card-title">{{ blog.body }}</h5>
            <p class="card-text">{{ blog.pub_date }}</p>
        </div>
        </div>
    {% endfor %}
  {% comment %} {% for blog in blogs.all %}
    <div class="card">
      <h5 class="card-header">{{ blog.title }}</h5>
      <div class="card-body">
        <h5 class="card-title">{{ blog.body }}</h5>
        <p class="card-text">{{ blog.pub_date }}</p>
        
        <!-- 해시태그 목록 보이는 곳 -->
        {% for hashtag in blog.hashtags.all %}
          <span>{{ hashtag.name }}</span>
        {% endfor %}
        <br>
        <a href="{% url 'edit' pk=blog.pk %}" class="btn btn-primary">수정</a>
        <a href="{% url 'remove' pk=blog.pk %}" class="btn btn-primary">삭제</a>
        <a role="button" class="btn btn-primary" href="{% url 'comment' blog.id %}">댓글</a>

        <hr>
        <div>
        <!-- 댓글 목록 보이는 곳 -->
          {% for comment in blog.comments.all %}
        <p> {{ comment }} </p>
          <div class = "button">
            <a role="button" class="btn-outline-secondary" href="{% url 'comment_edit' blog.id comment.id %}">댓글수정</a>
            <a role="button" class="btn-outline-danger" href="{% url 'comment_remove' blog.id comment.id %}">댓글삭제</a>
         
          </div>
        {% endfor %}
      </div>
{% endfor %} 
    </div>
    <br>
  {% endfor %} {% endcomment %}
  

{% endblock %}

crud/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>또니 과제5_crud+comment+hashtag</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

  <!-- Plugin CSS -->
  <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/freelancer.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">ddony assignment_hashtag</a>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'home' %}" >Home</a>
          </li>
          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'newblog' %}">글쓰기</a>
          </li>
          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'hashtag' %}">태그추가</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Header -->
  <header class="masthead bg-primary text-white text-center">
    <div class="container">
      <img class="img-fluid mb-5 d-block mx-auto" src="{% static 'img/love.png' %}" alt="">
      <h1 class="text-uppercase mb-0">또니의 게시판입니당</h1>
      <br>
      
      <h2 class="font-weight-light mb-0">ಇ게시글을 올려주세요ಇ</h2>
    </div>
  </header>

  <!-- Portfolio Grid Section -->
  <section class="portfolio" id="portfolio">
    <div class="container">
       {% block content %}  
      <h2 class="text-center text-uppercase text-secondary mb-0">list( ღ'ᴗ'ღ )</h2><br>
              
        {% endblock %}
      </div>
  </section>


  <!-- Footer -->
  <footer class="footer text-center">
    <div class="container">
      <div class="row">
        <div class="col-md-4 mb-5 mb-lg-0">
          <h4 class="text-uppercase mb-4"></h4>
          <p class="lead mb-0">성공회대학교
            <br>멋쟁이 사자처럼 7기</p>
        </div>
        <div class="col-md-4 mb-5 mb-lg-0">
          <h4 class="text-uppercase mb-4"></h4>
          <ul class="list-inline mb-0">
            <li class="list-inline-item">
              <a class="btn btn-outline-light btn-social text-center rounded-circle" href="https://www.facebook.com/profile.php?id=100017691130015" target="_blank">
                <i class="fab fa-fw fa-facebook-f"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn btn-outline-light btn-social text-center rounded-circle" href="https://www.instagram.com/s2_sohyuns2/" target="_blank">
                <i class="fab fa-fw fa-linkedin-in"></i>
              </a>
            </li>
          </ul>
        </div>
        <div class="col-md-4">
          <h4 class="text-uppercase mb-4">M:N</h4>
          <h4 class="lead mb-0">해시태그 생성/수정/삭제</h4>
        </div>
      </div>
    </div>
  </footer>

  <div class="copyright py-4 text-center text-white">
    <div class="container">
      <small>Copyright &copy; 글로컬IT학과 이소현</small>
    </div>
  </div>

  <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
  <div class="scroll-to-top d-lg-none position-fixed ">
    <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
      <i class="fa fa-chevron-up"></i>
    </a>
  </div>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

  <!-- Contact Form JavaScript -->
  <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
  <script src="{% static 'js/contact_me.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/freelancer.min.js' %}"></script>

</body>

</html>